package y2024.day08

import com.natpryce.hamkrest.assertion.assertThat
import com.natpryce.hamkrest.equalTo
import org.junit.Ignore
import org.junit.Test
import kotlin.Int.Companion.MIN_VALUE

class ResonantCollinearityTest {

    @Test
    fun simplifiedExamplePartOne() {
        val simpleInput = """............
........0...
.....0......
.......0....
....0.......
............
............
............
............
............
............
............"""
        val puzzle = ResonantCollinearity(simpleInput)
        assertThat(puzzle.solvePartOne(), equalTo(10))
    }

    @Test
    fun examplePartOne() {
        val puzzle = ResonantCollinearity(testInput)
        assertThat(puzzle.solvePartOne(), equalTo(14))
    }

    @Test
    fun actualPartOne() {
        val puzzle = ResonantCollinearity()
        assertThat(puzzle.solvePartOne(), equalTo(357))
    }

    @Test
    fun examplePartTwo() {
        val puzzle = ResonantCollinearity(testInput)
        assertThat(puzzle.solvePartTwo(), equalTo(34))
    }

    @Test
    fun actualPartTwo() {
        val puzzle = ResonantCollinearity()
        assertThat(puzzle.solvePartTwo(), equalTo(1266))
    }

}


private const val testInput = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
